### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by parsibox** [Srar/telegram-socks5-proxy#2]
hi
what is problem?

```
91.xxx.4.xx<-> 91.xxx.4.xxx:5222 connect
149.154.166.120 <-> 149.154.166.120:443 connect
149.154.166.120 <-> 149.154.166.120:443 connect
unable to connect to remote server: This socket has been ended by the other party
```

**Comment by Srar** [comment]
The proxy should running on server that unbanned country

**Comment by parsibox** [comment]
my server is not banned
![image](https://user-images.githubusercontent.com/12513476/39618363-9b4ca41a-4f98-11e8-840e-5edcb1ddcaa2.png)

**Comment by Srar** [comment]
emmmm...maybe you can use Wireshark to find what's happened in networking

**Comment by parsibox** [comment]
i see only this
```
* TLSv1.2 (IN), TLS alert, Client hello (1):
* Empty reply from server
* Connection #0 to host 94.xxx.98.xxx left intact
curl: (52) Empty reply from server

```

**Comment by parsibox** [comment]
and when start your code this say : 
```
(node:3021) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by Srar** [comment]
nodejs version?

**Comment by omidgfx** [comment]
my server is in germany, but still telegram not connecting, so what should i do? does my server needs any kind of SSL certificates ?

**Comment by Srar** [comment]
@pejmanchatrrooz 
may i have your server ip and password of root? I will debug proxy on your server.

**Comment by parsibox** [comment]
my node version is 10

**Comment by parsibox** [comment]
i can send Remote Desktop ( anydesk ) for you

**Comment by Srar** [comment]
@parsibox please send it to my email(a1020938070@gmail.com).

**Comment by parsibox** [comment]
sent

**Comment by Srar** [comment]
and I tested on node10 with vultr, it work well.

**Comment by parsibox** [comment]
i test with ip ( not work )
i test with domain ( not work )
you can try it with dose anysesk

**Comment by yushijinhun** [comment]
I don't think there is a way to bypass DPI without modifying the Telegram client. For personal use, you can choose any other proxy protocol (eg. shadowsocks). But if you want to make it available to others, the best solution is to set up a server in your nation to relay requests.

**Comment by sirenityapps** [comment]
@parsibox I have the same problem, and big thanks to you for starting this topic. I'm actually writing my test implementation of socks5 for telegram, and pissed off because can't understand what is going on. I realizes that it's telegram problem or something else. I tried other way to connect to telegram over Socks5 using this project https://github.com/schors/tgdante2 , and it doesn't works, but it was working a few weeks ago, sooo i think we have to wait or something like this. 
Also, can you please write me if you solve your issue or have some info?

**Comment by parsibox** [comment]
ok
if it solved , i write here

**Comment by Srar** [comment]
Hi! Telegram has released a new proxy protocol with encrypting. You can try it.
https://github.com/TelegramMessenger/MTProxy

![img_1b2dade35501-1](https://user-images.githubusercontent.com/12068066/41133531-0ebd91ee-6afa-11e8-896f-10af4142fa84.jpeg)

**Comment by parsibox** [comment]
mtproxt is okey
